project:
  type: website
  output-dir: docs
website:
  title: "Thomas Sandmann's personal blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/tomsing1
      - icon: linkedin
        href: https://www.linkedin.com/in/thomas-sandmann/
      - icon: twitter
        href: https://twitter.com/thomas_sandmann
format:
  html:
    theme: sandstone
    css: styles.css

editor: source

